url: http://panox.github.io/
baseurl: /panox.github.io

# Site settings
title: Panos Palos
email: panospalos123@gmail.com
description: "This is a personal portfolio site for Panagiotis Papantonopoulos"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/panox
  - title: github
    url: http://github.com/panox


# Build settings
markdown: kramdown
permalink: pretty